### ISSUE TITLE
Program Size on large Resolution 

### ISSUE THREAD

**Issue by Vistaking** [nickrod518/Migrate-WindowsUserProfile#17]
When you launch the ps1 file by right-clicking the file and selecting Run with Powershell the size of the program is good once it starts backing up the files opening up command prompt the ps1 app resizes to a small window . Screen Resolution is 3000 x 2000 
![resize](https://cloud.githubusercontent.com/assets/26915656/24690703/772ce60e-1983-11e7-87bc-766c0f85d6e4.jpg)

**Comment by WilliamMyers1** [comment]
Is this by any chance a surface book pro?

I'll see if I can recreate this behaviour. Can you please tell me what %
windows is set to scale objects and windows to on this machine?

**Comment by Vistaking** [comment]
Yes it is a SurfaceBook not a Pro  .  The Scale Percentage is 200 % ( Recommended ) .

**Comment by nickrod518** [comment]
The Scale Percentage is what's causing the issue. Unfortunately, this form does not use any type of scaling or responsive design, so it will not look right unless your Scale Percentage is at 100%. I wish I had the time to redesign the form to use anchors and other features that would allow scaling, but I simply have no experience with that nor do I have the time.
