### ISSUE TITLE
How to execute the Script for independent instances of Scanstate and Loadstate? Confused!

### ISSUE THREAD

**Issue by ferozekhan267oa** [nickrod518/Migrate-WindowsUserProfile#19]
Here is my test use case. I have a VM1 with 2 local admin accounts (1st the built in account by name Administrator and the 2nd is another account by name Admin).
Admin is the main account where I have my documents, favs, shortcuts, music, videos, wallpapers and app settings. I was able to successfully run the old computer scanstate with the script after selecting the account for migration and got the USMT.MIG file at C:\Temp\MigrateStore\<ComputerName>\USMT.

Now I login to the built in Administrator account and delete my Admin User Profile. I wish to run the loadstate independantly within the Administrator account and Migrate the Admin account back using the USMT.MIG. Not sure how? Documentation doesnt talk about such scenario.

Is this even possible to Scanstate and Loadstate independantly? Would be great to have this feature. please advice.

**Comment by nickrod518** [comment]
I'm a little confused so I'm going to restate your scenario to make sure I'm understanding. You migrated Administrator and Admin accounts to a new VM. You then logged into Administrator and deleted Admin. You now want to reload Admin. Is that right?

If so, the USMT.MIG data is deleted upon a successful migration so you'll need to run the save state again. You can indeed run the scan and load functions independently, just uncheck the "Save on new computer" on the save tab and instead type in the path you want the data saved to (it can be local, a network UNC path or even a USB drive). After you have another copy of the save data, run the load again but select "Change" under the save state source and specify where you saved the data to. Remember, the data will be removed if it's a success, so make a copy if you're planning on doing this more than once.

I hope this answers your question.

**Comment by nickrod518** [comment]
Closing because it's been a month with no response.
