### ISSUE TITLE
Some small bugs and an issue with loadstate

### ISSUE THREAD

**Issue by Pandha64** [nickrod518/Migrate-WindowsUserProfile#22]
For me no matter if I use 32bit or 64 bit, the program wants to run x86 scanstate, as workaround I created two seperate folders in which on of them I put the amd64 scanstate in x86.

Then I noticed some small errors in the script: There is an error in line: 1248 from invoke USMTGUI.ps1 (it lists Save State Destination while it should be something like select profiles.

The issue which I am not able to resolve: the loadstate script has 2 spaces to many between henk and /nocompress, any idea how to resolve this?

Example syntax:
loadstate.exe C:\TEMP\MigrationStore\LT-7L51HV1 /i:C:\TEMP\MigrationStore\LT-7L51HV1\Config.xml /mu:DEPCARTS\Henk:DOMAIN\Henk   /nocompress /l:C:\TEMP\MigrationStore\LT-7L51HV1\load.log /progress:C:\TEMP\MigrationStore\LT-7L51HV1\load_progress.log /c /v:13

Kind regards,

Henk

**Comment by Pandha64** [comment]
As comment on my comment, in the latest version the loadstate seem to work normal.
I will test this tomorrow, I do see a small typo in invoke-USMTGUI line: 1274
This states currently: Save State Destination, while it should be something like "Profile Selection"

Also in my first test on an x64 machine it looks for the USMT binaries in the x86 USMT folder, so it seem that the command in Config.ps1 line 44 to 49 is ignored and by default assumes it is x86

**Comment by nickrod518** [comment]
I'm glad to hear the first issue was resolved. Also, thanks for pointing out the typo. I tested on my computer and it appears to select the appropriate x64 binaries for USMT. Can you run this on the machine and see if PowerShell correctly identifies its bittage:
`(Get-WmiObject Win32_OperatingSystem).OSArchitecture -eq '64-bit'`

**Comment by davidtgbe** [comment]
On W10:
(Get-WmiObject Win32_OperatingSystem).OSArchitecture
64 bits

The key is the extra 's' char. I've solved replacing the line

```
if ((Get-WmiObject Win32_OperatingSystem).OSArchitecture -eq '64-bit') { 
```

with:
`((Get-WmiObject Win32_OperatingSystem).OSArchitecture -match '64') {`
