### ISSUE TITLE
How to add /listfiles into the script

### ISSUE THREAD

**Issue by Vistaking** [nickrod518/Migrate-WindowsUserProfile#29]
Is it possible to add $Logs = "`"/listfiles:$Destination\FilesMigrated.log`" to the script

**Comment by nickrod518** [comment]
Thanks for the suggestion. I've added it.

**Comment by Vistaking** [comment]
No problem and thank you.



________________________________

**Comment by Vistaking** [comment]
When you have some free time can you replace the Recycle Bin backup with the Downloads folder .

A lot of people like to store things in the downloads folder .



________________________________

**Comment by nickrod518** [comment]
@Vistaking just wanted to let you know I finally got around to adding the Downloads folder. If you still use this tool, please test it out and let me know what you think.

**Comment by Vistaking** [comment]
Hi Nick

Just tested out the new version with the Downloads folder option . Worked great backed up the downloads folder files .


________________________________

**Comment by nickrod518** [comment]
Awesome! Thank you for testing.

**Comment by Vistaking** [comment]
Only issue I see is the resolution of the application while its backing up . When you launch it the size is fine its when its backing the files up it gets smaller. But I think its on my end cause I have a high resolution.



________________________________

**Comment by nickrod518** [comment]
Oh I bet it's the DPI scaling. If you have Windows 10 I think it will
automatically set your DPI to like 125% and this app was not developed with
scaling in mind.

**Comment by Vistaking** [comment]
Yes I have windows 10 . Mine is set to 200% cause it’s recommended .

On Nov 21, 2018, at 12:23 PM, Nick Rodriguez <notifications@github.com<mailto:notifications@github.com>> wrote:

Oh I bet it's the DPI scaling. If you have Windows 10 I think it will
automatically set your DPI to like 125% and this app was not developed with
scaling in mind.

**Comment by Vistaking** [comment]
Hi nick

Would it be possible to add the function of moving to a new domain and a new user name in that new domain . USMT syntax is loadstate \\server\share\migration\mystore /mu:contoso\user1:fabrikam\user2 /i:migdocs.xml /i:migapp.xml

Reference from : https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-migrate-user-accounts





On Nov 21, 2018, at 12:23 PM, Nick Rodriguez <notifications@github.com<mailto:notifications@github.com>> wrote:

Oh I bet it's the DPI scaling. If you have Windows 10 I think it will
automatically set your DPI to like 125% and this app was not developed with
scaling in mind.

**Comment by nickrod518** [comment]
Sorry for not responding sooner. I don't think this is a feature I'll get
around to anytime soon but you are welcome to submit another issue to the
repo. If you or someone else were to add the feature and submit a pull
request I would accept it.

**Comment by Vistaking** [comment]
No worries . I don’t have access to do a request .



________________________________
