### ISSUE TITLE
Default extra directories to include

### ISSUE THREAD

**Issue by WatersMike2410** [nickrod518/Migrate-WindowsUserProfile#30]
Hi,

firstly congratulations on your script, it's working pretty good.

There's only one thing that doesn't work. I tried to include a standard directory as follows in the Config.ps1, but it does not show up if I run Invoke-USMTGUI.ps1. 

`# Default extra directories to include`
`$DefaultExtraDirectories = @('C:\Program Files (x86)\IBM\Notes\Data')`

I looked in the source code of Invoke-USMTGUI.ps1, and there is no reference to $DefaultExtraDirectories, so it might be just missing.

Thanks
Mike

**Comment by nickrod518** [comment]
Thank you for pointing this out. Apologies for the time it's taken for me to address the issue, but the latest commit should have this resolved.

**Comment by WatersMike2410** [comment]
Cool, it's working now as expected.

Thanks again for your work!
