### ISSUE TITLE
Old Computer name

### ISSUE THREAD

**Issue by NathanTheGr8** [nickrod518/Migrate-WindowsUserProfile#36]
I get this when I run the script. I notice I only get it with my Config.ps1 file and not the default one. I will dig in to see what is causing this but wanted to note it for right now.

    Get-ChildItem : Cannot find path 'C:\Users\davisn1\AppData\Local\Temp\IXP000.TMP\Scripts\OldComputer' because it does
    not exist.
    At C:\Users\davisn1\AppData\Local\Temp\IXP000.TMP\Invoke-USMTGUI.ps1:2341 char:27
    + ... erScripts = Get-ChildItem -Path "$PSScriptRoot\Scripts\OldComputer" | ...
    +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (C:\Users\davisn...pts\OldComputer:String) [Get-ChildItem], ItemNotFound
    Exception
        + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

    Get-ChildItem : Cannot find path 'C:\Users\davisn1\AppData\Local\Temp\IXP000.TMP\Scripts\NewComputer' because it does
    not exist.
    At C:\Users\davisn1\AppData\Local\Temp\IXP000.TMP\Invoke-USMTGUI.ps1:2385 char:27
    + ... erScripts = Get-ChildItem -Path "$PSScriptRoot\Scripts\NewComputer" | ...
    +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (C:\Users\davisn...pts\NewComputer:String) [Get-ChildItem], ItemNotFound
    Exception
        + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

**Comment by NathanTheGr8** [comment]
Ok, so I think I figured it out. If you create the path projectRoot\Scripts\OldComputer and projectRoot\Scripts\NewComputer it fixes the issue. If you go further and put files in ether directory it auto adds them to the scripts tab. A pretty nice feature.

The fix, therefore, would be to create these directories in the project. However, this creates an issue for people (like myself) that want to package your project with the Create-EXEFromPS1 project. I submit a pull request to create these directories but I would like to hear your thoughts on moving the Config.ps1 and Scripts directory into USMT. That way you can call Create-EXEFromPS1 and just include one additional directory.

**Comment by nickrod518** [comment]
I read this after commenting on the pull request. So you're saying out
everything under the USMT folder so that it plays nice with the other
project that compiles it into an exe? I think that's a good idea that
doesn't cause too much disturbance.
