### ISSUE TITLE
Small architecture detection bug found

### ISSUE THREAD

**Issue by PfhorEver** [nickrod518/Migrate-WindowsUserProfile#47]
Great tool! You should be proud of your work.

I wanted to let you know that the architecture detection logic in Config.ps1 will not properly detect a 32 bit platform as the values for Win32_OperatingSystem OSArchitecture will likely be '64-bit' or '32-bit'.

Instead of: 
`} elseif ($Arch -match '86') {`

It should (probably) read:
`} elseif (($Arch -match '86') -or ($Arch -match '32')) {`

**Comment by WilliamMyers1** [comment]
I noticed this as well when I migrated a 32-bit system, it was defaulting
to ARM

**Comment by nickrod518** [comment]
Thanks, I updated
`} elseif ($Arch -match '86') {`

to read
`} elseif (($Arch -match '86') -or ($Arch -match '32')) {`

Please test and let me know if you still have problems.
