### ISSUE TITLE
Powershell 3.0 Required for profile selection

### ISSUE THREAD

**Issue by kno005** [nickrod518/Migrate-WindowsUserProfile#48]
On several computers when trying to migrate clicking "Select Profile(s) to Migrate" did nothing. I ended up migrating all profiles that logged in within 90 days and it was successful. Upon further digging with the console open and clicking select profile(s) I get the following:

```
Out-GridView : A parameter cannot be found that matches parameter name 'OutputMode'.
At C:\Users\kno005\Desktop\Migrate-WindowsUserProfile-master\Invoke-USMTGUI.ps1:1360 char:68
+                 Out-GridView -Title 'Profile Selection' -OutputMode <<<<  Multiple
    + CategoryInfo          : InvalidArgument: (:) [Out-GridView], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.OutGridViewCommand
```

Looking into it, OutputMode was not introduced until PowerShell 3.0. I'm not sure if it is better to change to make it 2.0 compatible somehow or just make a note that 3.0 is required.

**Comment by kno005** [comment]
This applies to the "Custom XML(s)" button also.

I also just noticed that you have a warning about running PowerShell less than 3.0 that I didn't notice before. So, maybe disable these buttons also?

**Comment by nickrod518** [comment]
Thanks for the suggestion. I've disabled the custom xml button and the profile selection button if PowerShell version is less than 3.0 in this [commit](https://github.com/nickrod518/Migrate-WindowsUserProfile/commit/fa59ab1198bfbeea19a5932ce96794a8a19df7dd).
