### ISSUE TITLE
How to pick "Old Computer" in the New Computer Tab?

### ISSUE THREAD

**Issue by TheNickness92** [nickrod518/Migrate-WindowsUserProfile#50]
Hello,

I'm liking the tool, but have one question. I'm not doing these side by side, i'm doing one, then the other later on and storing the mig's on a server.

When i login to the new computer and go to the "new computer" tab, it seems to pull the old computer name only from the most recently added backup on that server directory, and does not let me choose out of say, the 4 i'm working on.

**Comment by nickrod518** [comment]
I think I see what you're saying. That should probably be given in an Out-GridView and allow you to select which backup. I'll leave this issue open but to be honest I won't get to it for a while. I would suggest putting your migrations into subfolders on that share as a workaround.

**Comment by TheNickness92** [comment]
> I think I see what you're saying. That should probably be given in an Out-GridView and allow you to select which backup. I'll leave this issue open but to be honest I won't get to it for a while. I would suggest putting your migrations into subfolders on that share as a workaround.

That's actually the workaround we ended up using, and honestly it's super simple, so i'm not complaining. If a fix ever comes around that will be cool, but this is perfectly fine either way.

This tool has saved my guys so much headache, i don't think anyone will complain about the subfolders haha! Thanks for putting this together!
