### ISSUE TITLE
Is there a way to Exclude directories?

### ISSUE THREAD

**Issue by TheNickness92** [nickrod518/Migrate-WindowsUserProfile#57]
Hi Nick,

First of all, we are still loving the tool!

We did have a question/request though:

We notice there is a windows defender folder in programdata that continues to hang up and error out on some systems. It's not an issue itself, cause that directory gets recreated on new images.

Really we just wanted to know if there was a way to tell the backup to exclude that folder so it doesn't get stuck on it?

Thanks!

**Comment by TannerFilip** [comment]
This is way late, but it looks like you can do that in Config.ps1. https://github.com/nickrod518/Migrate-WindowsUserProfile/blob/ebca6fe96581354d52f1fda67c60648605303951/USMT/Config.ps1#L54

**Comment by ghost** [comment]
Hi Nick

I would like to exclude onedrive directories what is the syntax that i need to use to exclude the directory i found a post online that suggests the following pattern :

 

> 
pattern type="File">%USERPROFILE%\OneDrive*\* [*]</pattern

>

**Comment by ghost** [comment]
I ended up adding that line into this section of code in invoke-USMTGUI.ps1 and it seems to work, if there is a better way im all ears :) 

"@
    # Exclude each file pattern user has added to the Default Exclude Files
    $DefaultExcludeFiles | ForEach-Object {
        $ExcludeFile = $_

        $ExcludeFilesXML += @"
                        <pattern type="File">%USERPROFILE%\OneDrive*\* [*]</pattern>

"@

**Comment by rothrock88** [comment]
what's the syntax on actually excluding file types? For example, I'm trying to exclude .PSTs from a migration. I've tried putting "*.pst" between the parenthesis on line 54 of config.ps1, but it doesn't seem to be working.

**Comment by sirwasi** [comment]
I'd also love to have some comprehensive instructions on how to exclude Files (Syntax, Wildcarts etc) and especially whole Directories. Thanks.

**Comment by nickrod518** [comment]
For syntax on excluding files/directories with USMT I recommend you review the [USMT docs](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-exclude-files-and-settings). Embarrassingly, it's been so long since I worked on this project that I cannot recall how the exclude files/directories functionality in the config file works. It might be easier for you to create a custom migration xml file and use that instead of the config file.

**Comment by ripclawffb** [comment]
To exclude files, you can set something like this in the Config.ps1.

```
$DefaultExcludeFiles = @("*.pst", "Sample*", "Outlook.txt")
```

This will exclude all PST files, anything that starts with Sample and any files named Outlook.txt. I tested this on a machine and it works as expected.

**Comment by nickrod518** [comment]
> To exclude files, you can set something like this in the Config.ps1.
> 
> ```
> $DefaultExcludeFiles = @("*.pst", "Sample*", "Outlook.txt")
> ```
> 
> This will exclude all PST files, anything that starts with Sample and any files named Outlook.txt. I tested this on a machine and it works as expected.

Thanks so much, I've approved and merged your pull request which includes examples in the config.
