### ISSUE TITLE
Overwrite destination files

### ISSUE THREAD

**Issue by BiosError** [nickrod518/Migrate-WindowsUserProfile#64]
I just started using this tool, but I've found it to be very well written, simple to configure and easy to use.  Good job and thanks!

I'd like to migrate the user's Chrome profile (%localappdata%\google\chrome\user data) and maybe even Firefox and Edge.
When I added that location, the restore says to make sure the destination folder already exists so I started up Chrome which creates it automatically. After the restore, I found the chrome profile was not live so I looked in the folder. What I found was that every file from the old PC was placed in the User Data folder as a numbered copy like filename(1). As a test, I performed another migration over the top of that one and it created filename(2) files.

In the Desktop, Documents, etc. folders, it looks like it places copies of any files that have changed and, based on the speed of the second restore, probably skips any files that are identical.

Is there a way to force it to overwrite all migrated data on the new pc?
Is there a way to force it to overwrite only specific data on the new pc?

Thanks in advance!

**Comment by nickrod518** [comment]
Are you doing the restore while logged in as that user? Maybe try logging in as a different user and restoring from there.

Thanks,
Nick

**Comment by BiosError** [comment]
That works.
Thanks.
