### ISSUE TITLE
Automatic selection of a Custom XML file

### ISSUE THREAD

**Issue by Syriius** [nickrod518/Migrate-WindowsUserProfile#68]
Is it possible to skip the custom xml files button and directly select the MigApp.XML file?

**Comment by nickrod518** [comment]
Try and update this line to your custom config path:Migrate-WindowsUserProfile/Invoke-USMTGUI.ps1 at f7fb4fc8dc20b9a9c1ec314cd4f9411d4af247eb · nickrod518/Migrate-WindowsUserProfilegithub.comThanks,NickOn Feb 2, 2023, at 9:50 AM, Syriius ***@***.***> wrote:﻿
Is it possible to skip the custom xml files button and directly select the MigApp.XML file?

**Comment by Syriius** [comment]
Thank you Guys
